DEFAULT_CONFIG = {
    "SECRET_KEY":"dev-secret-key",
    "WTF_CSRF_ENABLED":"FALSE",
    'SQLALCHEMY_DATABASE_URI':"",
    'SQLALCHEMY_POOL_SIZE':"30",
    'SQLALCHEMY_POOL_RECYCLE':"3600",
    'SQLALCHEMY_ECHO':"TRUE"
}
